create database ecommerce_cart;
use ecommerce_cart;

-- Insert users
insert into users(name, email, password, phone, address, image_url, role) values('Admin Admin', 'admin@gmail.com', '111111', '12345689', 'Bankok US', 'https://thumbs.dreamstime.com/b/admin-sign-laptop-icon-stock-vector-166205404.jpg', 'ADMIN');
insert into users(name, email, password, phone, address, image_url, role) values('BabyBoy', 'bb@gmail.com', '111111', '098758215', 'Viet Nam', 'https://muaxegiatot.vn/wp-content/uploads/2020/06/sieu-xe-la-gi-muaxegiatot-vn.jpg', 'USER');

-- Insert Categories
insert into categories(name, image_url) values('Shoes', 'https://media.istockphoto.com/photos/white-sneaker-on-a-blue-gradient-background-mens-fashion-sport-shoe-picture-id1303978937?b=1&k=20&m=1303978937&s=170667a&w=0&h=az5Y96agxAdHt3XAv7PP9pThdiDpcQ3otWWn9YuJQRc=');
insert into categories(name, image_url) values('Watch', 'https://www.helioswatchstore.com/sites/default/files/balmain-NA.jpg');
insert into categories(name, image_url) values('Computer', 'https://www.splashtop.com/wp-content/uploads/remote-desktop-page-image1-minified.jpg');
insert into categories(name, image_url) values('Clothes', 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8Y2xvdGhlc3xlbnwwfHwwfHw%3D&w=1000&q=80');
insert into categories(name, image_url) values('Glasses', 'https://m.media-amazon.com/images/I/31LxGZgP7FL._SL500_.jpg');
insert into categories(name, image_url) values('Smart Phone', 'https://img.etimg.com/thumb/width-640,height-480,imgsize-63506,resizemode-1,msid-56153038/wealth/spend/6-ways-to-put-your-old-smartphone-to-use/mobile-app-640-480_bccl.jpg');

-- insert Products
insert into products (u_id, name, category_id, price, description, image_url) values(1, 'White Sneaker', 1, '1000', "These are a staple! I brought these to NYC and walked everywhere with them! I got them a whole size bigger because my size wasn't available but it worked out with chunky socks!", 'https://media.istockphoto.com/photos/white-sneaker-on-a-blue-gradient-background-mens-fashion-sport-shoe-picture-id1303978937?b=1&k=20&m=1303978937&s=170667a&w=0&h=az5Y96agxAdHt3XAv7PP9pThdiDpcQ3otWWn9YuJQRc=');
insert into products (u_id, name, category_id, price, description, image_url) values(1, 'Blue Sneaker', 1, '2000', 'Very cute boots! A little on the small size. If you are planning to wear with thin socks, the boots are true to size. However, if you are planning to wear with thicker socks, I would recommend sizing up', 'https://cdn.vox-cdn.com/thumbor/qouGiDTFDkjLzuzMpc-Nj3xjO88=/0x0:2000x1196/1200x800/filters:focal(840x438:1160x758)/cdn.vox-cdn.com/uploads/chorus_image/image/70267766/a16z_rtfkt_sneakers.0.jpg');
insert into products (u_id, name, category_id, price, description, image_url) values(1, 'Focus Sneaker', 1, '3000', 'Very cute but unfortunately too big on me and my size is out of stock :(', 'https://cf.shopee.ph/file/5139c66abeb9d177886ad21bfa7e0f82');
insert into products (u_id, name, category_id, price, description, image_url) values(1, 'Life is a tough Sneaker', 1, '4000', 'Super Cute. Runs on the small side so if your in between size up. Can dress up or down. Love it!!!', 'https://image.made-in-china.com/202f0j00iKWYrLZMHUqD/New-Style-Fashion-Shoe-Daddy-Shoes-Men-s-Shoe-Sneakers-Shoe-Casual-Shoe.jpg');
insert into products (u_id, name, category_id, price, description, image_url) values(1, 'Sneaker Buti', 1, '5000', 'Love love love this top. Dress up and ability to dress down with jeans.', 'https://image.made-in-china.com/2f0j00AugGRWdJrhcB/2019-Spring-New-Style-Super-Hot-Fashion-Sports-Men-Shoes.jpg');
insert into products (u_id, name, category_id, price, description, image_url) values(1, 'Shoes For Men', 1, '5000', 'True To Size / some curves / height tall', 'https://image.made-in-china.com/2f0j00AugGRWdJrhcB/2019-Spring-New-Style-Super-Hot-Fashion-Sports-Men-Shoes.jpg');
insert into products (u_id, name, category_id, price, description, image_url) values(1, 'Sneaker', 1, '5000', 'Cheap material, no zipper to slide into. Terrible design.', 'https://image.made-in-china.com/2f0j00AugGRWdJrhcB/2019-Spring-New-Style-Super-Hot-Fashion-Sports-Men-Shoes.jpg');
insert into products (u_id, name, category_id, price, description, image_url) values(1, 'Watch Silver', 2, '500', 'Runs SMALLWEIRD necklineIncredibly cheap for the $$$', 'https://cdn.shopify.com/s/files/1/0027/2357/7914/articles/A22A1281_1200x.jpg?v=1597178612');
insert into products (u_id, name, category_id, price, description, image_url) values(1, 'Watch Gold', 2, '230', 'Estimated Delivery : Jan 11 - Jan 12 FREE INTERNATIONAL SHIPPING FOR ORDERS ABOVE $100 USD', 'https://image.shutterstock.com/image-vector/vector-cartoon-classic-mens-wrist-260nw-615428642.jpg');
insert into products (u_id, name, category_id, price, description, image_url) values(1, 'Smart Watch', 2, '8780', "On my feet 8+ hours a day in these at home...feet are warm without overheating...sooo comfy...and then there's the cuteness factor 😍", 'https://images.fpt.shop/unsafe/fit-in/585x390/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2021/8/15/637646632610588704_samsung-galaxy-watch-4-den-small-2.jpg');
insert into products (u_id, name, category_id, price, description, image_url) values(1, 'Apple Watch', 2, '780', 'I not would recommend this item, but I bought a pair for my sister', 'https://cdn.hoanghamobile.com/i/productlist/dsp/Uploads/2020/11/04/se-40.png');
insert into products (u_id, name, category_id, price, description, image_url) values(1, 'Black Watch', 2, '340', 'Very comfortable, and this Color is gourges', 'https://m.media-amazon.com/images/I/71gdBQP+qGL._UY741_.jpg');
insert into products (u_id, name, category_id, price, description, image_url) values(1, 'Redux Analogue Black', 2, '720', 'Be the first to know about new arrivals, sales & promos by submitting your email! You can opt out at any time. privacy policy', 'https://images-na.ssl-images-amazon.com/images/I/819AnkHJAlL._UY445_.jpg');
insert into products (u_id, name, category_id, price, description, image_url) values(1, 'Apple Watch White', 2, '543', 'Download our super easy-to-use app available for your iPhone, iPad and Android.', 'https://cdn.hoanghamobile.com/i/productlist/dsp/Uploads/2020/11/04/se-40.png');